# Generated by Django 5.1.6 on 2025-03-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Grave', 'Grave'), ('Muy grave', 'Muy grave')], max_length=15)),
                ('requiereInter', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trastorno',
            fields=[
                ('id_trastorno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('edad', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(default=' ', max_length=30)),
                ('email', models.CharField(blank=True, default=' ', max_length=100, null=True, unique=True)),
                ('nombreAcudiente', models.CharField(max_length=35)),
                ('apellidoAcudiente', models.CharField(max_length=35)),
                ('documentoAcu', models.CharField(max_length=10)),
                ('telefonoAcu', models.CharField(blank=True, max_length=15, null=True)),
                ('emailAcu', models.CharField(max_length=50)),
                ('grado', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B')], max_length=3)),
                ('id_diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pacientes.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('id_diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pacientes.diagnostico')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('PIAR', models.TextField(blank=True, null=True)),
                ('detalles_PIAR', models.TextField(blank=True, null=True)),
                ('id_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.diagnostico')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id_intervencion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_intervencion', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
                ('detalles', models.TextField()),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.historiaclinica')),
            ],
        ),
    ]
