# Generated by Django 5.1.6 on 2025-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='detalleInter',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='fechaInter',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
