# Generated by Django 5.1.6 on 2025-03-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_diagnostico_detalleinter_diagnostico_fechainter'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='id_estudiante',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Pacientes.estudiantes'),
            preserve_default=False,
        ),
    ]
