# Generated by Django 5.1.6 on 2025-03-29 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0003_diagnostico_id_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='trastorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pacientes.trastorno'),
        ),
    ]
