# Generated by Django 5.1.6 on 2025-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0004_diagnostico_trastorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='observaciones',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='plan',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='id_diagnostico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
