# Generated by Django 4.2.10 on 2025-04-24 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0005_diagnostico_observaciones_diagnostico_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='plan',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='estado_actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='intervenciones',
            field=models.ManyToManyField(blank=True, to='Pacientes.intervencion'),
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True)),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.historiaclinica')),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pacientes.plantratamiento'),
        ),
    ]
