# Generated by Django 4.2.10 on 2025-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0006_remove_diagnostico_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
