# Generated by Django 5.1.6 on 2025-04-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0007_alter_historiaclinica_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='motivoIn',
            field=models.TextField(default='Intento de suicidio'),
            preserve_default=False,
        ),
    ]
