# Generated by Django 5.1.6 on 2025-05-08 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0008_intervencion_motivoin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_personales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='evaluacion_psicologica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='Pacientes.estudiantes'),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='tipo_intervencion',
            field=models.CharField(choices=[('Intervención individual', 'Intervención individual'), ('Intervención grupal', 'Intervención grupal'), ('Intervención familiar', 'Intervención familiar'), ('Intervención psicoeducativa', 'Intervención psicoeducativa'), ('Intervención en crisis', 'Intervención en crisis'), ('Intervención comunitaria o social', 'Intervención comunitaria o social'), ('Intervención preventiva', 'Intervención preventiva')], max_length=100),
        ),
    ]
