# Generated by Django 5.1.6 on 2025-05-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0009_historiaclinica_antecedentes_familiares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='recomendaciones',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='usar_PIAR',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='PIAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto_estudiante', models.TextField()),
                ('objetivos', models.TextField()),
                ('ajustes_curriculares', models.TextField()),
                ('ajustes_didacticos', models.TextField()),
                ('apoyos_requeridos', models.TextField()),
                ('responsables', models.TextField()),
                ('seguimiento', models.TextField()),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.historiaclinica')),
            ],
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='PIAR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pacientes.piar'),
        ),
    ]
