# Generated by Django 5.1.6 on 2025-05-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0010_remove_historiaclinica_recomendaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='usar_PIAR',
            field=models.BooleanField(default=False),
        ),
    ]
