# Generated by Django 5.1.6 on 2025-05-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0011_alter_historiaclinica_usar_piar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='PIAR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pacientes.piar'),
        ),
    ]
