# Generated by Django 5.1.6 on 2025-05-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0012_alter_historiaclinica_piar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='PIAR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='usar_PIAR',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PIAR',
        ),
    ]
