# Generated by Django 5.1.6 on 2025-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0013_alter_historiaclinica_piar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
