# Generated by Django 5.2.1 on 2025-05-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0015_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
