# Generated by Django 5.2.1 on 2025-05-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0016_cita_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='resumen',
        ),
        migrations.AddField(
            model_name='observacion',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
