# Generated by Django 5.2.1 on 2025-05-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0018_cita_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='resumen',
        ),
    ]
