# Generated by Django 5.1.6 on 2025-05-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0019_remove_cita_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('calificacion', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SeguimientoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('avance', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='Pacientes.plantratamiento')),
            ],
        ),
    ]
